spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: postgres
    password: 1008
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  classformat:
    ignore: true